server {
	listen 8080 default_server;
	listen [::]:8080 default_server;
	listen 8443 ssl default_server;
	listen [::]:8443 ssl default_server;
	server_name _;

	# Add SSL
	ssl_certificate /etc/letsencrypt/live/domain.foo/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/domain.foo/privkey.pem;
	include /etc/nginx/ssl/options-ssl-nginx.conf;
	ssl_dhparam /etc/nginx/ssl/ssl-dhparams.pem;
	
	return 444;
	
}
