server {
	
	listen 8080;
	server_name domain.foo www.domain.foo;

	location / {
		return 301 https://$host$request_uri;
	}
}
	
server {

	listen 8443 ssl;
	server_name domain.foo www.domain.foo;

	ssl_certificate /etc/letsencrypt/live/domain.foo/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/domain.foo/privkey.pem;
	include /etc/nginx/ssl/options-ssl-nginx.conf;
	ssl_dhparam /etc/nginx/ssl/ssl-dhparams.pem;

	location / {
		proxy_pass http://nginx-astroalce:8080;
		proxy_http_version 1.1;
		
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-Proto $scheme;
	
		# Needed to proper redirection between the 2 container	
		proxy_redirect off;
	}
	

	# Add Error Page (404-50x)
}
