server {
	
	listen 8080;
	server_name git.domain.foo;
	
	location / {
		return 301 https://$host$request_uri;
	}
}
server {

	listen 8443 ssl;
	server_name git.domain.foo;
	
	ssl_certificate /etc/letsencrypt/live/domain.foo/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/domain.foo/privkey.pem;
	
	include /etc/nginx/ssl/options-ssl-nginx.conf;
	ssl_dhparam /etc/nginx/ssl/ssl-dhparams.pem;
	allow 10.13.13.0/24;
	allow 127.0.0.1;
	deny all;
	location / {
		
		modsecurity_rules 'SecRuleRemoveById 930130';
		modsecurity_rules 'SecRuleRemoveById 920440';
		proxy_pass http://gitea:3000;
		proxy_http_version 1.1;

		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-Proto $scheme;

		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
	}
	access_log /tmp/nginx/log/gitea_access.log;
	error_log /tmp/nginx/log/gitea_error.log;

}
